export { MainTableGrid } from './ui/MainTableGrid'
export { columnsMain, columnsReady, columnsRename } from './model/gridStyles'
export {useMainStore} from './lib/useMainStore'
export {useReadyStore} from './lib/useReadyStore'
export {useRenameStore} from './lib/useRenameStore'
export type {TRowRename, TRenameFile, TRowReady, TRowMain} from './model/types'